SELECT TO_CHAR (SYSDATE, 'DD-MON-YYYY HH24:MI:SS')
FROM DUAL;
select USER
from dual;
select TO_date('12/25/2020', 'mm/dd/yyyy') - ROUND(SYSDATE)AS DIFF
from dual;
select TO_CHAR(CYCLEDATE, 'MONTH') AS MONTH, LAST_DAY(CYCLEDATE) - CYCLEDATE AS
"Days Between Payday and first of next month"
from PAYDAY;
select CONCAT(CONCAT(FIRSTNAME,' '), RPAD(LASTNAME,50, '.')) AS NAME, '('||
SUBSTR(PHONE,1,3)||')'||SUBSTR(PHONE,5,8) AS PHONE
FROM ADDRESS
ORDER BY LASTNAME, FIRSTNAME ASC;
select RPAD(ZIP,3) AS ZIP, COUNT(RPAD(ZIP,3)) AS COUNT
from ADDRESS
GROUP BY ZIP;
select PERSON, INSTR(PERSON, ' ')
from LEDGER;
